
recipe: default.v1

assistant_id: my_custom_bot

language: en

pipeline:
# 1. First, we split the text into words (tokenize)
- name: WhitespaceTokenizer

# 2. Then, we create features (numbers) for the classifier to use
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

# 3. Now, the main classifier can understand the intent and entities
- name: DIETClassifier
  epochs: 100

# 4. The fallback classifier runs after to check confidence
- name: FallbackClassifier
  threshold: 0.4

# 5. Finally, map any synonyms
- name: EntitySynonymMapper

# policies:
# - name: MemoizationPolicy
# - name: RulePolicy
# - name: UnexpecTEDIntentPolicy
#   max_history: 5
#   epochs: 100
# - name: TEDPolicy
#   max_history: 5
#   epochs: 100

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100